services:
  api:
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: python -m app.run
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - qdrant
      - mongo
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/logs
      - FORCE_COLOR=1
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1
    shm_size: "1g"
    ipc: host
    stdin_open: true
    tty: true

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  qdrant_storage:
  mongo_data:
