name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      qdrant:
        # Use a known stable tag instead of `latest` to avoid unexpected regressions
        image: qdrant/qdrant:v1.7.3
        ports:
          - 6333:6333
          - 6334:6334
        options: >-
          --health-cmd "curl -f http://localhost:6333/health || exit 1"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 20

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl mongodb-mongosh
    
    - name: Install Python dependencies
      working-directory: ./Backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov pytest-mock httpx
    
    - name: Set up test environment variables
      working-directory: ./Backend
      run: |
        echo "JWT_SECRET=test-secret-key-for-ci" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://localhost:27017" >> $GITHUB_ENV
        echo "MONGO_DB=metta_test_db" >> $GITHUB_ENV
        echo "QDRANT_HOST=localhost" >> $GITHUB_ENV
        echo "QDRANT_PORT=6333" >> $GITHUB_ENV
        echo "COLLECTION_NAME=test_collection" >> $GITHUB_ENV
        echo "ADMIN_EMAIL=admin@test.com" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=test_admin_password" >> $GITHUB_ENV
        echo "MIN_SCORE=0.0" >> $GITHUB_ENV
    
    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB..."
        for i in {1..30}; do
          if mongosh --host localhost:27017 --eval "db.adminCommand(\"ping\")" > /dev/null 2>&1; then
            echo "MongoDB is ready!"
            break
          fi
          echo "Attempt $i/30: MongoDB not ready yet, waiting..."
          sleep 2
        done
    
    - name: Wait for Qdrant to be ready (extended + diagnostics)
      run: |
        echo "Waiting for Qdrant..."
        READY=0
        for i in {1..60}; do
          if curl -f http://localhost:6333/health > /dev/null 2>&1; then
            echo "Qdrant is ready!"
            READY=1
            break
          fi
          echo "Attempt $i/60: Qdrant not ready yet, waiting 5s..."
          sleep 5
        done

        if [ "$READY" -ne 1 ]; then
          echo "Qdrant did not become healthy after waiting. Gathering diagnostics..."
          echo "=== curl /health output ==="
          curl -v http://localhost:6333/health || true
          echo "=== docker ps (all) ==="
          docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}" || true
          # try to print logs from containers whose image contains 'qdrant'
          QDRANT_IDS=$(docker ps -a --filter ancestor=qdrant/qdrant:v1.7.3 --format '{{.ID}}' || true)
          if [ -n "$QDRANT_IDS" ]; then
            for id in $QDRANT_IDS; do
              echo "=== docker logs for $id ==="
              docker logs --tail 200 $id || true
            done
          else
            echo "No qdrant containers found by ancestor filter; attempting name grep..."
            QDRANT_IDS=$(docker ps -a --format '{{.ID}} {{.Names}} {{.Image}}' | grep -i qdrant | awk '{print $1}' || true)
            if [ -n "$QDRANT_IDS" ]; then
              for id in $QDRANT_IDS; do
                echo "=== docker logs for $id ==="
                docker logs --tail 200 $id || true
              done
            else
              echo "Could not find qdrant container to print logs."
            fi
          fi
          echo "Failing the job because Qdrant is not healthy."
          exit 1
        fi
    
    - name: Run unit tests
      working-directory: ./Backend
      run: |
        pytest tests/unit -v --cov=app --cov-report=xml --cov-report=term-missing
    
    - name: Run integration tests
      working-directory: ./Backend
      run: |
        pytest tests/integration -v --cov=app --cov-append --cov-report=xml --cov-report=term-missing
    
    - name: Generate coverage report
      working-directory: ./Backend
      run: |
        pytest --cov=app --cov-report=html --cov-report=term-missing || true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./Backend/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Check test coverage threshold
      working-directory: ./Backend
      run: |
        pytest --cov=app --cov-report=term-missing --cov-fail-under=60 || echo "Coverage below threshold, but continuing..."
